#
# SPDX-FileCopyrightText: Copyright 2022, 2024 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#

[tool.black]
target-version = ['py310']

[tool.pytest.ini_options]
markers = [
    "header_test",
    "module_table_test",
    "model_sequence_test",
    "model_resource_test",
    "constant_test"
]
